### ISSUE TITLE
How can this be configured (e.g. s3 for cache in parameters.yml) and the image version should be specified or `pullPolicy: IfNotPresent` will mean it never changes

### ISSUE THREAD

**Issue by violuke** [flyimg/helm-charts#4]
Thanks for the chart. I'm looking forward to trying this out. Just a few initial thoughts. Cheers!

**Comment by sadok-f** [comment]
Thank you @violuke for opening this issue.
We're still working on the Helm chart to add options to override the configuration in `parameters.yml` file, we'll release it soon.
regarding the image version, it is set in `Chart.yaml` file under`appVersion` variable, where it gets appended to the repository variable when used in the deployment.yml file.
for each new version, we'll release a new helm-chart as well to update the `appVersion` and add any changes needed.

for the `pullPolicy: IfNotPresent` if the current version e.g. `flyimg/flyimg:1.4.12` is not in the current node, k8s will download it, otherwise use the existing one.
when we release a new version and the helm chart get updated, k8s will download the new requested version.

I hope I answered your questions :)

**Comment by violuke** [comment]
Ah, that makes sense. That's really useful, thank you for the reply :smile:

**Comment by sadok-f** [comment]
Hi @violuke we actually released a new helm chart version that allow the possibility to overriding the default configuration in parameters.yml file
Can you give it a try?
Any feedback is much appreciated!
Thanks!
